### PR TITLE
Multiversion-index support

### PR DESCRIPTION
**Pull request by yakunink**
Hello, 
We talked a bit in IRC about multiversion-index support. Here is changes that will allow this to happen. And the most important thing is that it wont brake backward compatibility. 

Details:
CPAN::Common::Index::Mirror->search_packages method can return more than one module matched. It allows us to add more than one version of same module to 02packages index.
We can handle multiversion response from CPAN::Common::Index::Mirror. This will allow people to have multiversion in local CPANs and will not brake backward compatibility.

### CODE REVIEW

**Comment by miyagawa** [comment]
> CPAN::Common::Index::Mirror->search_packages method can return more than one module matched.

It _can_ return multiple packages as the API signature allows, but the implementation uses a binary search when `package` is given, and i do not believe it will work correctly.

Although having multiple versions for the same package in 02packages is something I've been thinking about, this needs to happen after having some consensus among the generators and consumers (CPAN.pm, PAUSE, etc.) I'd be happy to discuss in the Perl toolchain summit in May.

**Comment by yakudzo** [comment]
Good day,
I've read Search::Dict module that CPAN::Common::Index uses.
Search::Dict implemented with ability to make binary search even on files with duplicate keys.  And `look` function will return first appearance of looking key. You can check this here https://metacpan.org/source/DAGOLDEN/Search-Dict-1.07/lib/Search/Dict.pm#L100. When it compares element and compare function returns 0 it does not exit search loop but goes further to make a better result.

So I do believe nothing will fail with multi-version index file.

**Comment by yakunink** [comment]
Hello,
I've switched from Sort::Versions to version.pm and added couple of test.
The last one is for binary search witch only enabled when file is big enough.
Hope you like this solution. (;

**Comment by shadowcat-mst** [comment]
What does this achieve over multiple opan configs (since opan doesn't require all packages on disk, just N 02packages files) ?

**Comment by yakunink** [comment]
Our homemade modules on darkpan grow rapidly in numbers and versions. And installing the latest version from darkpan is rather bad practice than good.

If your code depends on modules inside darkpan that your teammates deploy you would always need to unpin specific dists, update bundle, update cpanfile and then pin module back again. With opan you need to know dist filename first so you are not able to use Version Ranges from CPAN::Meta::Spec.

Multivesion 02packages resolves this problems. You will need update your deps only in cpanfile, you can use version ranges and if needed you still can install latest version.
The greatest thing is that this patch does not brake backward compatibility of Menlo and uses already build-in features that CPAN::Common::Index::Mirror has.

**Comment by lamoz** [comment]
Hi! Im interested in multiversions too.

I think that multiversions would be useful for darkpans. We often make non-backwards compatible versions of modules (applications and libraries) in our company.
And it is pain to build distributive (tarball with all dependencies included) of old application version which depends on certain old module version.
I think that it is not practical to manifest dependancies in two places - Build.PL/Makefile.PL/cpanfile and inside special opan index.

Multiversions for me is the ability to have multiple versions of a Module in darkpan index and tools' (like cpan/cpanm/carton/carmel) support for such indexes.
Now cpanm fails with "==x.y.z" dependancy and newer "x.y.z+1" version of a module in darkpan index.

**Pull request closed without merging**
