### PR TITLE
If paths of commands contain spaces, quote them

### PR DESCRIPTION
**Pull request by skaji**
Address #545 

Use our own which() instead of File::Which::which() directly;
if paths of commands contain spaces, quote them.

### CODE REVIEW

**Comment by skaji** [comment]
Oops, sorry, I should have be careful about `$Config{make}`;
It will be called via `[$self->{make}, "build"]` or something.
So, in unix, we should't quote that,
and in windows, we may quote that twice.

**Comment by miyagawa** [comment]
Hm, but how come would cpanm (pre Menlo) work? because that's what it does in there.

**Comment by miyagawa** [comment]
ok actually shell_quote in cpanminus Utils doesn't do the double quoting.

**Comment by skaji** [comment]
Yeah, cpanminus avoids double quoting on Win32 
https://github.com/miyagawa/cpanminus/blob/devel/lib/App/cpanminus/script.pm#L2849

On unix, if $Config{make} contains spaces, I think cpanminus does not work well.
But that rarely happens on unix:)

**Pull request merged**
