### PR TITLE
Split Menlo::CLI::Compat into a separate Legacy package

### PR DESCRIPTION
**Pull request by miyagawa**
Merging App::cpamninus::script into Menlo::CLI::Compat is a good idea only for bug fixes that can go into one package rather than multiple. I quickly realized that downstream clients such as App::cpm uses and heavily depends on the internal representation of Menlo::CLI::Compat (or App::cpanminus::script), so that refactoring that code is almost impossible.

This PR splits the Menlo::CLI::Compat *again* from Menlo, so that downstream clients can depend on the specific implementation and behaviors of cpanm 1.7.

This also adds back App::cpanminus::script package as a shim, so that any (ab)users will still make their hack work, hopefully.

### CODE REVIEW

**Comment by skaji** [comment]
@miyagawa Thank you very much for this.

Once you merge this PR, and release Menlo-Legacy to CPAN, then I will use it.

A couple of questions:

* Do you need to move Menlo::Dependency, Menlo::Util, etc, to Menlo-Legacy too? (I don't have a strong option, just asking)
* It seems that Menlo::Legacy has "use 5.008_005" line. I hope you lower that requirement when you release it to CPAN.

**Comment by miyagawa** [comment]
> Do you need to move Menlo::Dependency, Menlo::Util, etc, to Menlo-Legacy too? (I don't have a strong option, just asking)

No, these will stay in Menlo core and i will refactor and update it as we go, but will keep the public API. Please don't use the internals of these modules.

> It seems that Menlo::Legacy has "use 5.008_005" line. I hope you lower that requirement when you release it to CPAN.

Good catch it's just the default of Milla.

**Comment by skaji** [comment]
> No, these will stay in Menlo core and i will refactor and update it as we go, but will keep the public API. Please don't use the internals of these modules.

I understand!

**Comment by miyagawa** [comment]
This has been merged and released as Menlo-Legacy-1.9019.

**Comment by skaji** [comment]
Thanks for releasing this!

But we still have "use 5.008_005" line ...
https://github.com/miyagawa/cpanminus/blob/devel/Menlo-Legacy/lib/Menlo/Legacy.pm#L4

**Comment by miyagawa** [comment]
Fixed that.

**Pull request merged**
