### PR TITLE
Enable static_install

### PR DESCRIPTION
**Pull request by miyagawa**
If there's `x_static_install` in META, cpanm will use its bundled version of Module::Build::Tiny (a little modified fork) to build, test and install modules.

- [x] support dynamic_config = 0 as well since they go the similar path
- [ ] skip installing build dependencies (?)
- [x] add test to ensure PERL_MB_OPT and `-l` are respected
- [x] disable for perl < 5.12, (or if uninstall_shadows is set)
- [x] disable if sudo option if set
- [x] <s>treatdynamic_config = 0 in 1.x as static install (experimental)</s>
- [x] check test failure

Note this is a pull request against the menlo branch (cpanm 2.0) and merging it won't bring the feature to the cpanm 1.x releases.

### CODE REVIEW

**Comment by miyagawa** [comment]
re: dynamic_config = 0 in 1.4 semantics

Here's the list of dists with META 1.4 yml file and dynamic_config = 0
https://gist.github.com/miyagawa/14db2ca19dc9c1a53a47

Most of them are the dzil settings which sets dynamic_config = 0 by default, and while I think many of they can actually be built statically, there are distributions that have the wrong value with the default, for example https://metacpan.org/release/DAGOLDEN/PPI-XS-0.902

**Comment by karenetheridge** [comment]
I filed https://rt.cpan.org/Ticket/Display.html?id=105517 for PPI-XS.

**Comment by miyagawa** [comment]
I ran a quick scanner to find out *.xs/*.h files in the list, and came up with 49 distributions. it might not be the full list, but that will probably cover most of clearly wrong XS dists. https://gist.github.com/miyagawa/21b1e02784df7acb8aa2

Most of them are dzil, so they can add MetaJSON to include 2.0 which has the different meaning of dynamic_config = 0 to be preferred.

**Comment by miyagawa** [comment]
While 49 are not that many, it might not be worth filing bugs for all dists, rather I can add a workaround/heuristics to see if a dist is made with dzil, has only META.yml and has some *.xs files in there.

**Comment by miyagawa** [comment]
Handling dynamic_config = 0 in 1.x as what 1.x doc says is (as I expected) a controversial move.

One thing it wasn't described yet is that in Module::Install (and old versions of MakeMaker) don't differentiate build/test requires in the past, so everything was in `build` deps. So even if we handle 1.4 `dynamic_config=0` as static, we have to make sure `build` deps are installed for `test` install runs.

**Comment by miyagawa** [comment]
IRC discussion has led to an agreement that static_install can only work with a narrow audience at first, so that limiting it to perl 5.12+ (to avoid uninstall_shadows) and disable when `--sudo` is set, is reasonable. Distributions will need to be shipped with .PL files for a foreseeable decade anyway.

**Comment by miyagawa** [comment]
Discussion and implementation experiments have started and I'm happy to move this PR against devel to make a release sooner.

**Comment by miyagawa** [comment]
Merged this branch to menlo branch, we'll see how it can be shipped and enabled.

**Pull request merged**
