### PR TITLE
Successful CI tests

### PR DESCRIPTION
**Pull request by kiwiroy**
For some time the Travis tests have been failing.

The default mirror is missing some of the distributions required by the tests.

This pull request changes the versions, hopefully maintaining the logic and intent of the tests.

### CODE REVIEW

**Comment by miyagawa** [comment]
Thank you so much for this! It seems some tests are still failing...

**Comment by skaji** [comment]
I think most test failures come from distributions being removed from CPAN (and only being in backpan).

So is it time to change
http://www.cpan.org to https://cpan.metacpan.org :)
https://github.com/miyagawa/cpanminus/blob/devel/lib/App/cpanminus/script.pm#L1399

**Comment by kiwiroy** [comment]
@skaji That was my first approach, although I used the following in the affected test scripts.

```perl
local $ENV{PERL_CPANM_OPT} = '--mirror https://cpan.metacpan.org';
```

Travis appears to be having some issues prematurely ending jobs as e550de was [successful](https://travis-ci.org/kiwiroy/cpanminus/builds/341194307) for many of [#830 failures](https://travis-ci.org/miyagawa/cpanminus/builds/341211215)

**Comment by miyagawa** [comment]
fixing the CI by using metacpan (backpan) index in tests.

**Pull request closed without merging**
